before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - package_name: perfcheck
    homepage: https://github.com/zacikpet/perfcheck
    maintainer: Peter Žáčik
    description: This tool is used to evaluate the compliance of a service with service-level objectives specified in the API description of the service.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    recommends:
      - k6
    release: "1.0.0"

snapcrafts:
  - name: perfcheck
    publish: true
    summary: Automatic SLO compliace evaluation
    description: This tool is used to evaluate the compliance of a service with service-level objectives specified in the API description of the service.
    grade: stable
    confinement: classic
    license: MIT
    base: core18

dockers:
  - image_templates:
      - zacikpet/perfcheck