before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapcrafts:
  - name: perfcheck
    publish: true
    summary: Automatic SLO compliace evaluation
    description: This tool is used to evaluate the compliance of a service with service-level objectives specified in the API description of the service.
    grade: stable
    confinement: classic
    license: MIT
    base: core18

