// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "summary": "Hello",
                "responses": {},
                "x-perf-check": {
                    "errorRate": 0.1,
                    "latency": 100
                }
            }
        },
        "/group/a": {
            "post": {
                "summary": "TestRoute",
                "responses": {},
                "x-perf-check": {
                    "errorRate": 0.05,
                    "latency": 150
                }
            }
        },
        "/group/b": {
            "patch": {
                "summary": "TestRoute",
                "responses": {},
                "x-perf-check": {
                    "errorRate": 0.1,
                    "latency": 150
                }
            }
        },
        "/test-route": {
            "get": {
                "summary": "TestRoute",
                "responses": {},
                "x-perf-check": {
                    "errorRate": 0.2,
                    "latency": 250
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
